# transfer-api-pod.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: transfer-api-deployment
  labels:
    app: transfer-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: transfer-api
  template:
    metadata:
      labels:
        app: transfer-api
    spec:
      containers:
        - name: transfer-api
          image: tiagorv0/transfer-api:latest
          env:
            - name: TransferAccountApi
              value: http://transfer-account-clusterip:8300
            - name: DatabaseOptions__ConnectionString
              value: mongodb://guest:guest@transfer-database:27017
            - name: RabbitMq__Host
              value: rabbitmq-clusterip-service
          ports:
          - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: transfer-api-clusterip
spec:
  selector:
    app: transfer-api
  ports:
  - port: 8100
    targetPort: 8080
    name: transfer-api
    protocol: TCP
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: transfer-api
spec:
  selector:
    app: transfer-api
  ports:
  - port: 8100
    targetPort: 8080
    name: transfer-api
    protocol: TCP
    nodePort: 31810
  type: NodePort
